pipeline {
    agent any
    parameters {
        string(defaultValue: "", description: "something", name: "stringName")
        booleanParam(defaultValue: false, description: "something", name: "booleanName")
        choice(choices: ["BOB", "BOBSON"], description: "something", name: "choiceName")
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                echo "Boolean set to ${booleanName}\n"
                echo "String set to ${stringName}\n"
                echo "Boolean set to ${choiceName}\n"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
