pipeline {
    agent any
    environment {
        def myString = "hi"
        def myBool = true
        def myNumber = 10
    }
    parameters {
        string(defaultValue: "ceva", description: "something", name: "stringName")
        booleanParam(defaultValue: false, description: "something", name: "booleanName")
        choice(choices: ["BOB", "BOBSON"], description: "something", name: "choiceName")
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                echo "Boolean set to ${booleanName}\n"
                echo "String set to ${stringName}\n"
                echo "Boolean set to ${choiceName}\n"

                echo "variable Boolean set to ${myBool}\n"
                echo "variable String set to ${myString}\n"
                echo "variable Number set to ${myNumber}\n"
                script {
                    if (true) {
                        echo "Build number: ${env.BUILD_NUMBER}"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
